USE data_analysis_project;

SELECT * 
FROM customer_shopping_details;



-- BUSSINESS INSIGHT QUESTIONS 

-- Q1 Which category generates higher revenue

SELECT category, ROUND(SUM(purchase_amount), 2) AS highest_revenue  FROM 
customer_shopping_details
GROUP BY category
ORDER BY highest_revenue desc;


-- Bussiness problem : Company does not knwo which category controbutes most to revenue

-- Impact: 1- Help priotizing high_performance cateogory 
-- 		2- Optimize inventory planning
-- 		3-imporove marketing ROI 



-- Q2- Are discount actually increasing purchase value

SELECT 
discount_applied,
ROUND(SUM(purchase_amount), 2) AS total_revenue ,
ROUND(AVG(purchase_amount), 2) AS avg_purchase 
FROM 
customer_shopping_details
GROUP BY discount_applied;


-- Q3 - What is the total revenue generated by male and female customers

SELECT 	gender, ROUND(SUM(purchase_amount), 2) AS total_revenue  FROM 
customer_shopping_details
GROUP BY gender;


-- Q4- Which customer using a discount but still spent more then the avg purchased amount


SELECT 
customer_ID,
purchase_amount,
discount_applied
FROM customer_shopping_details 
WHERE  discount_applied='Yes' AND purchase_amount > (SELECT AVG(purchase_amount) FROM customer_shopping_details);



-- Q5- Which are the top/bottom 5 product  which has highest avg  review rating 

SELECT 
	item_purchased,
	ROUND(AVG(review_rating), 2) AS avg_rating
FROM customer_shopping_details
group by item_purchased
ORDER BY avg_rating DESC
LIMIT 5;


SELECT 
	item_purchased,
	ROUND(AVG(review_rating), 2) AS avg_bottom_rating
FROM customer_shopping_details
group by item_purchased
ORDER BY avg_bottom_rating ASC
LIMIT 5;



-- Q6-Average purchase:standard vs Express shipping

SELECT 
	shipping_type,
    Count(DISTINCT customer_ID ) as order_placed,
    ROUND(AVG(purchase_amount), 2) as avg_purchase
FROM customer_shopping_details
WHERE shipping_type IN ('Express','Standard')
GROUP BY shipping_type;


-- Q7- Do suscrie customers spend more AS compare avg speed and total revenue beteween sub or non sub

SELECT 
	subscription_status,
    COUNT(customer_ID) as users,
    ROUND(SUM(Frequency_of_Purchases),2) as avg_speed,
    ROUND(AVG(purchase_amount),2) as avg_revenue,
    ROUND(SUM(purchase_amount),2) as total_revenue
FROM customer_shopping_details
GROUP BY subscription_status;


-- Q8- top 5 products with highest discount usages %

SELECT 
	item_purchased,
    COUNT(item_purchased) as total_no_item_sold,
    COUNT(CASE WHEN discount_applied = 'Yes' THEN 1 END) AS number_of_time_sold_discount_applied,
    COUNT(CASE WHEN discount_applied = 'Yes' THEN 1 END)  *100.0 / COUNT(*) AS percent_ofdiscount
FROM customer_shopping_details
GROUP BY  item_purchased
ORDER BY percent_ofdiscount desc
LIMIT 5;

-- Q9- Segment customer into new, returning and loyal based on thier purchase and show the count of each segment

SELECT 
	CASE
		WHEN Previous_Purchases='1' THEN 'NEW CUSTOMER'
		WHEN Previous_Purchases BETWEEN 5 AND 15 THEN 'Returning customer'
	ELSE 'Loyal Customers'
END  AS customer_segment,
COUNT(*) AS customers_count
FROM customer_shopping_details
GROUP BY customer_segment;

-- Q10- What are the top 3 most purchased item within each category 


WITH CTE AS
(
select
	category,
    item_purchased,
    COUNT(item_purchased) as most_purchased,
    RANK() OVER(PARTITION BY category ORDER BY COUNT(item_purchased) desc ) as rank_item
FROM customer_shopping_details
GROUP BY category, item_purchased    
)
SELECT  *FROM CTE 
WHERE rank_item <= 3
;


-- Q11= Are customer who are repeat buyer also likely to suscribe ?

SELECT
	CASE 
		WHEN Previous_Purchases > 5 THEN 'Repeat Buyers'
        ELSE 'Normal Buyer'
	END AS customer_type,
    subscription_status,
    COUNT(*) AS  customer_count
FROM customer_shopping_details
GROUP  BY CASE 
		WHEN Previous_Purchases > 5 THEN 'Repeat Buyers'
        ELSE 'Normal Buyer'
	END, subscription_status;
    
    
    
--     
-- Q12= What is the revenue controbution of each age group



SELECT 
	CASE
		WHEN age BETWEEN 18 AND 25 THEN '18-25'
        WHEN age BETWEEN 26 AND 33 THEN '26-35'
        WHEN agE BETWEEN 35 AND 50 THEN '35-50'
        ELSE '50+'
	END AS age_groups,
    ROUND(SUM(purchase_amount),2) AS total_amount_rev
FROM customer_shopping_details
GROUP BY CASE
		WHEN age BETWEEN 18 AND 25 THEN '18-25'
        WHEN age BETWEEN 26 AND 33 THEN '26-35'
        WHEN agE BETWEEN 35 AND 50 THEN '35-50'
        ELSE '50+'
	END 
    ORDER BY total_amount_rev DESC ;
